
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files (x86)/cloudflared/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/ttorr/.dotnet/tools/"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/ttorr/.platformio/penv/Scripts/"
    searched_directories:
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja-build.com"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja-build.exe"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja-build"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja.com"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja.exe"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/ninja"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/samu.com"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/samu.exe"
      - "C:/Users/ttorr/Documents/GitHub/DTU_Shared_2026/MOP_2/.venv/Scripts/samu"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja-build.com"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja-build.exe"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja-build"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja.com"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja.exe"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/ninja"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/samu.com"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/samu.exe"
      - "C:/Program Files/Microsoft SQL Server/170/Tools/Binn/samu"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja-build.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja-build.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja-build"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/ninja"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/samu.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/samu.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files (x86)/cloudflared/ninja-build.com"
      - "C:/Program Files (x86)/cloudflared/ninja-build.exe"
      - "C:/Program Files (x86)/cloudflared/ninja-build"
      - "C:/Program Files (x86)/cloudflared/ninja.com"
      - "C:/Program Files (x86)/cloudflared/ninja.exe"
      - "C:/Program Files (x86)/cloudflared/ninja"
      - "C:/Program Files (x86)/cloudflared/samu.com"
      - "C:/Program Files (x86)/cloudflared/samu.exe"
      - "C:/Program Files (x86)/cloudflared/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/ttorr/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/ttorr/AppData/Local/Programs/Microsoft VS Code/bin/samu"
      - "C:/Users/ttorr/.dotnet/tools/ninja-build.com"
      - "C:/Users/ttorr/.dotnet/tools/ninja-build.exe"
      - "C:/Users/ttorr/.dotnet/tools/ninja-build"
      - "C:/Users/ttorr/.dotnet/tools/ninja.com"
      - "C:/Users/ttorr/.dotnet/tools/ninja.exe"
      - "C:/Users/ttorr/.dotnet/tools/ninja"
      - "C:/Users/ttorr/.dotnet/tools/samu.com"
      - "C:/Users/ttorr/.dotnet/tools/samu.exe"
      - "C:/Users/ttorr/.dotnet/tools/samu"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja-build.com"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja-build.exe"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja-build"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja.com"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja.exe"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/ninja"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/samu.com"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/samu.exe"
      - "C:/Users/ttorr/AppData/Local/GitHubDesktop/bin/samu"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja-build.com"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja-build.exe"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja-build"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja.com"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja.exe"
      - "C:/Users/ttorr/.platformio/penv/Scripts/ninja"
      - "C:/Users/ttorr/.platformio/penv/Scripts/samu.com"
      - "C:/Users/ttorr/.platformio/penv/Scripts/samu.exe"
      - "C:/Users/ttorr/.platformio/penv/Scripts/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\ttorr\\Documents\\GitHub\\DTU_Shared_2026\\MOP_2\\.venv/Scripts"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\windows\\system32"
        - "C:\\windows"
        - "C:\\windows\\System32\\Wbem"
        - "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Microsoft SQL Server\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\cloudflared\\"
        - "C:\\windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\ttorr\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\ttorr\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\ttorr\\.dotnet\\tools"
        - "C:\\Users\\ttorr\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\ttorr\\.platformio\\penv\\Scripts"
...
