CARD_W = 50
CARD_H = 75

COL_SPACING_X = 110
COL_START_X = 25
COL_START_Y = 70
COL_Y_STEP = int(CARD_H * 0.40)

FOUND_START_X = COL_START_X + 7 * COL_SPACING_X + 30
FOUND_START_Y = COL_START_Y
FOUND_Y_STEP = CARD_H + 20